# Generated by Django 6.0.2 on 2026-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplace',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
